apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherly-frontend
  namespace: weatherly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherly-frontend
  template:
    metadata:
      labels:
        app: weatherly-frontend
    spec:
      containers:
        - name: frontend
          image: sfalconi2001/weatherly-frontend:1.0.0-9f0fb8bcf4f2d1299c4b5b48c0a72cb221d69c35
          ports:
            - containerPort: 3000
