apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherly-frontend
  namespace: weatherly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherly-frontend
  template:
    metadata:
      labels:
        app: weatherly-frontend
    spec:
      containers:
        - name: frontend
          image: sfalconi2001/weatherly-frontend:latest
          ports:
            - containerPort: 3000
