apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherly-frontend
  namespace: weatherly
spec:
  template:
    spec:
      containers:
        - name: frontend
          image: sfalconi2001/weatherly-frontend:PLACEHOLDER
