name: Build and publish Frontend Dev Docker Image

on:
  push:
    branches: ["main"]
    paths:
      - "frontend/**"
      - "k8s/overlays/dev/frontend-image-patch.yaml"
      - ".github/workflows/build-push-frontend-dev.yml"
      - "k8s/base/frontend-deployment.yaml"
      - "k8s/overlays/dev/kustomization.yaml"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Read version
        run: |
          VERSION=$(node -p "require('./frontend/package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build & push image
        run: |
          IMAGE=sfalconi2001/weatherly-frontend:${VERSION}-${{ github.sha }}

          docker build -t $IMAGE ./frontend \
            --build-arg NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }} \
            --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}

          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Update frontend deployment
        run: |
          sed -i "s|image: .*|image: $IMAGE|" k8s/base/frontend-deployment.yaml

      - name: Commit image update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add k8s/base/frontend-deployment.yaml
          git commit -m "chore(dev): update frontend image to $IMAGE [skip ci]"
          git push
