name: Build and publish Frontend Dev Docker Image

on:
  pull_request:
    branches: ["main"]
    types: [closed, synchronize, reopened]
    paths:
      - "frontend/**"
      - "k8s/overlays/dev/kustomization.yaml"
      - github/workflows/build-push-frontend-dev.yml
permissions:
  contents: write

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Read version
        run: |
          VERSION=$(node -p "require('./frontend/package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build & push image
        run: |
          IMAGE=sfalconi2001/weatherly-frontend:${VERSION}-${{ github.sha }}

          docker build -t $IMAGE ./frontend \
            --build-arg NEXT_PUBLIC_API_KEY=${{ secrets.NEXT_PUBLIC_API_KEY }} \
            --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}

          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Update frontend deployment
        run: |
          sed -i "s|newTag: .*|newTag: ${VERSION}-${{ github.sha }}|" \
            k8s/overlays/dev/kustomization.yaml

      - name: Commit image update
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add k8s/overlays/dev/kustomization.yaml
          git commit -m "chore(dev): update frontend image tag to ${VERSION}-${{ github.sha }} [skip ci]"
          git push
